apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-liga3-weekday
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/part-of: league-simulator
    league: liga3
    action: start
    schedule-type: weekday
  annotations:
    description: "Start 3. Liga pods on weekdays at 19:15 Berlin time"
    berlin-time: "19:15"
    timezone: "Europe/Berlin"
spec:
  # 19:15 Berlin → 17:15 UTC (summer CEST)
  schedule: "15 17 * * 1-5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/name: pod-lifecycle-job
            app.kubernetes.io/component: scaler
            league: liga3
            action: start
        spec:
          serviceAccountName: pod-lifecycle-manager
          restartPolicy: OnFailure
          containers:
          - name: scaler
            image: bitnami/kubectl:1.28
            command:
            - kubectl
            - scale
            - deployment
            - league-updater-liga3
            - --replicas=1
            - -n
            - league-simulator
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            env:
            - name: DEPLOYMENT_NAME
              value: "league-updater-liga3"
            - name: TARGET_REPLICAS
              value: "1"
            - name: ACTION
              value: "start"