# This docker files needs to environment variables passed with -e at the run command:
# SHINYAPPS_TO_SECRET is the shinyapps secret
# RAPIDAPI_KEY is the RapidAPI key

# Start from a minimal Linux distribution
FROM rocker/tidyverse

# Setting environment variables
# Set the environment variables
ENV SHINYAPPS_IO_ACCOUNT=chrisschwer \
    SHINYAPPS_IO_TOKEN=3EBFA2C60C1438DAAA98FE4C0CAEC9AC


# Install necessary R packages
COPY packagelist.txt .
RUN while read in; do R -e "install.packages('$in')"; done < packagelist.txt

# Copy R scripts into the container
COPY RCode/ /RCode/

# source all the .R files
RUN Rscript -e "lapply(list.files('/RCode', pattern='\\.R$', full.names=TRUE), source)"

# Set up a CRON job
RUN echo '30 */1 * * * Rscript /RCode/update_all.R' > /etc/crontabs/root

# The command that starts the cron service
CMD ["crond", "-f", "-l", "8"]
