# This docker files needs to environment variables passed with -e at the run command:
# SHINYAPPS_TO_SECRET is the shinyapps secret
# RAPIDAPI_KEY is the RapidAPI key

# Start from a rocker r distribution distribution
FROM rocker/tidyverse:4.3.1

# Setting environment variables
# Set the environment variables
ENV SHINYAPPS_IO_ACCOUNT=chrisschwer \
    SHINYAPPS_IO_TOKEN=3EBFA2C60C1438DAAA98FE4C0CAEC9AC


# Install necessary R packages
COPY packagelist.txt .
RUN while read in; do R -e "install.packages('$in')"; done < packagelist.txt

# Install cron
RUN apt-get update && apt-get install -y cron

# Copy R scripts into the container
COPY RCode/ /RCode/

# Copy ShinyApp into the container
COPY ShinyApp/ /ShinyApp/

# Initialize the environment an make first update
RUN Rscript /RCode/update_all_leagues_init.R

# Set up a CRON job for every day at 14:45
RUN echo '45 14 * * * Rscript /RCode/update_all_leagues_loop.R' > /etc/crontab

# The command that starts the cron service
CMD ["cron", "-f"]
