apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-bl-weekend
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/part-of: league-simulator
    league: bl
    action: start
    schedule-type: weekend
  annotations:
    description: "Start Bundesliga pods on weekends at 17:15 Berlin time"
    berlin-time: "17:15"
    timezone: "Europe/Berlin"
spec:
  # 17:15 Berlin → 15:15 UTC (summer CEST)
  schedule: "15 15 * * 0,6"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true  # Start suspended for safety
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300  # 5 minutes max
      template:
        metadata:
          labels:
            app.kubernetes.io/name: pod-lifecycle-job
            app.kubernetes.io/component: scaler
            league: bl
            action: start
        spec:
          serviceAccountName: pod-lifecycle-manager
          restartPolicy: OnFailure
          containers:
          - name: scaler
            image: bitnami/kubectl:1.28
            command:
            - kubectl
            - scale
            - deployment
            - league-updater-bl
            - --replicas=1
            - -n
            - league-simulator
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            env:
            - name: DEPLOYMENT_NAME
              value: "league-updater-bl"
            - name: TARGET_REPLICAS
              value: "1"
            - name: ACTION
              value: "start"