apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-simulator
  labels:
    app: league-simulator
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: league-simulator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: league-simulator
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: league-simulator
        image: league-simulator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3838
          name: http
          protocol: TCP
        env:
        - name: RAPIDAPI_KEY
          valueFrom:
            secretKeyRef:
              name: league-simulator-secrets
              key: rapidapi-key
        - name: SHINYAPPS_IO_SECRET
          valueFrom:
            secretKeyRef:
              name: league-simulator-secrets
              key: shinyapps-secret
        - name: SEASON
          valueFrom:
            configMapKeyRef:
              name: league-simulator-config
              key: season
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /alive
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: league-simulator-data
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}