# Engine-selection regression net for update_elos_for_match.
#
# RCode/elo_aggregation.R:225 uses `if (exists("SpielNichtSimulieren"))` and
# falls back to a pure-R calculate_elo_update if the C++ primitive isn't loaded.
# This file pins:
#   1) The C++-path output (with SpielNichtSimulieren defined).
#   2) The R-fallback output via calculate_elo_update directly.
#   3) Cross-engine agreement across a parameter sweep.
#
# The agreement test's verdict is the load-bearing input to the Phase-2 PRD's
# Option A vs Option B branch (docs/prds/2026-05-03-simulation-engine-seam-phase-2.md).
#
# STALE-BINDING NOTE: RCode/RcppExports.R (generated by Rcpp::compileAttributes) defines
# SpielNichtSimulieren as a .Call("LeagueSimulator_SpielNichtSimulieren", PACKAGE =
# "LeagueSimulator", ...) stub. When source_rcode_modules() in helper-test-setup.R
# sources this file, it creates a broken binding that makes exists("SpielNichtSimulieren")
# return TRUE but the function fail at runtime. compile_cpp_files() then skips the
# Rcpp::sourceCpp step because the function already "exists".
#
# ensure_spiel_cpp() below detects the broken stub and force-recompiles from source.
# It uses BASE_PATH (set by helper-test-setup.R) to find the .cpp file regardless of
# the working directory during test execution.
#
# NOTE ON SHADOW-EXISTS PATTERN: The `with(list(exists = shadow_exists), ...)` pattern
# does NOT reliably shadow base::exists() inside update_elos_for_match because that
# function resolves `exists` in its own lexical scope (the environment where it was
# defined when elo_aggregation.R was sourced), not in the with() evaluation environment.
# Test 2 therefore directly exercises calculate_elo_update() — the fallback — rather
# than trying to hide SpielNichtSimulieren from update_elos_for_match's dispatch branch.

library(testthat)

# Resolve the absolute path to SpielNichtSimulieren.cpp using BASE_PATH if available
# (set by helper-test-setup.R), falling back to testthat::test_path() or a heuristic.
.spiel_cpp_path <- local({
  if (exists("BASE_PATH") && nchar(BASE_PATH) > 0) {
    file.path(BASE_PATH, "RCode", "SpielNichtSimulieren.cpp")
  } else {
    # testthat::test_path() resolves relative to the test file's directory
    tryCatch(
      file.path(testthat::test_path(), "..", "..", "RCode", "SpielNichtSimulieren.cpp"),
      error = function(e) "RCode/SpielNichtSimulieren.cpp"
    )
  }
})

# Ensure SpielNichtSimulieren is the compiled native function, not the stale RcppExports stub.
# The stale stub from RCode/RcppExports.R calls .Call("LeagueSimulator_SpielNichtSimulieren",
# PACKAGE = "LeagueSimulator") which fails because the LeagueSimulator package is not loaded.
# When the stub is present, exists("SpielNichtSimulieren") returns TRUE but the function
# errors on first call. We probe the function and recompile if broken.
ensure_spiel_cpp <- function() {
  is_broken <- tryCatch({
    if (!exists("SpielNichtSimulieren")) return(invisible(NULL))  # will be compiled below
    SpielNichtSimulieren(1500, 1500, 2, 0, 20, 100)
    FALSE  # no error
  }, error = function(e) TRUE)

  if (!exists("SpielNichtSimulieren") || is_broken) {
    if (!file.exists(.spiel_cpp_path)) {
      stop("SpielNichtSimulieren.cpp not found at: ", .spiel_cpp_path)
    }
    message("(Re)compiling SpielNichtSimulieren.cpp — stale stub detected or function missing")
    Rcpp::sourceCpp(.spiel_cpp_path)
  }
}

# Build a fixed match record and elo table for all three tests.
fixture_match <- function() {
  data.frame(
    teams_home_id = 1L,
    teams_away_id = 2L,
    goals_home = 2,
    goals_away = 0,
    stringsAsFactors = FALSE
  )
}

fixture_elos <- function() {
  data.frame(
    TeamID = c(1L, 2L),
    CurrentELO = c(1500, 1500),
    stringsAsFactors = FALSE
  )
}

test_that("update_elos_for_match returns C++-path ELOs when SpielNichtSimulieren is defined", {
  # Ensure the real compiled function is available (not the stale RcppExports stub).
  skip_if_not(file.exists(.spiel_cpp_path),
              paste("SpielNichtSimulieren.cpp not found at", .spiel_cpp_path))
  ensure_spiel_cpp()
  skip_if_not(exists("SpielNichtSimulieren"),
              "SpielNichtSimulieren could not be compiled; check Rcpp installation")

  result <- update_elos_for_match(fixture_elos(), fixture_match())

  # Hand-computed from SpielNichtSimulieren.cpp with mod_factor=20, home_advantage=100,
  # ELOs (1500, 1500), goals (2, 0):
  #   ELODeltaInv = away - home - homeAdv = 1500 - 1500 - 100 = -100
  #                 clamped to [-400, 400] -> -100 (no clamp needed)
  #   ELOProb     = 1 / (1 + 10^(-100/400)) = 1 / (1 + 10^(-0.25))
  #               = 1 / (1 + 0.5623413...) = 0.6400649...
  #   goalDiff    = 2 - 0 = 2
  #   result      = ((0 < 2) - (2 < 0) + 1) / 2 = 1.0
  #   goalMod     = sqrt(max(abs(2), 1)) = sqrt(2) = 1.41421356...
  #   ELOMod      = (1.0 - 0.6400649) * 1.41421356 * 20 = 10.18028...
  # home_new_elo  = 1500 + 10.18028 = 1510.18028
  # away_new_elo  = 1500 - 10.18028 = 1489.81972
  # Verified by Rscript: SpielNichtSimulieren(1500,1500,2,0,20,100) = 1510.1805 1489.8195
  expected_home <- 1500 + 10.18028
  expected_away <- 1500 - 10.18028

  expect_equal(result$CurrentELO[result$TeamID == 1L], expected_home, tolerance = 1e-4)
  expect_equal(result$CurrentELO[result$TeamID == 2L], expected_away, tolerance = 1e-4)
})

test_that("calculate_elo_update (R fallback) produces correct ELOs independently of SpielNichtSimulieren", {
  # We directly call calculate_elo_update — the pure-R fallback function that
  # update_elos_for_match uses when SpielNichtSimulieren is absent — to pin its
  # output independently of the engine-dispatch branch.
  #
  # The `with(list(exists = shadow_exists), update_elos_for_match(...))` approach
  # cannot shadow base::exists() inside update_elos_for_match because that function
  # resolves `exists` in its own lexical scope, not the with() environment.
  # Calling calculate_elo_update directly is simpler and unambiguous.
  #
  # Hand-computed from calculate_elo_update (elo_aggregation.R:252+) with
  # home_elo=1500, away_elo=1500, goals_home=2, goals_away=0:
  #   elo_diff       = (away_elo - home_elo - home_advantage) = (1500 - 1500 - 100) = -100
  #                    clamped: max(min(-100, 400), -400) = -100
  #   expected_prob  = 1 / (1 + 10^(-100/400)) = 0.6400649...
  #   goal_diff      = 2 - 0 = 2
  #   actual_result  = (sign(2) + 1) / 2 = 1.0
  #   goal_modifier  = sqrt(max(abs(2), 1)) = sqrt(2) = 1.41421356...
  #   elo_change     = (1.0 - 0.6400649) * 1.41421356 * 20 = 10.18028...
  #   home_elo       = 1500 + 10.18028 = 1510.18028
  #   away_elo       = 1500 - 10.18028 = 1489.81972
  expected_home <- 1500 + 10.18028
  expected_away <- 1500 - 10.18028

  r_result <- calculate_elo_update(1500, 1500, 2, 0)

  expect_equal(r_result$home_elo, expected_home, tolerance = 1e-4)
  expect_equal(r_result$away_elo, expected_away, tolerance = 1e-4)
})

test_that("C++ and R fallback engines produce equivalent ELO updates across a parameter sweep", {
  skip_if_not(file.exists(.spiel_cpp_path),
              paste("SpielNichtSimulieren.cpp not found at", .spiel_cpp_path))
  ensure_spiel_cpp()
  skip_if_not(exists("SpielNichtSimulieren"),
              "SpielNichtSimulieren could not be compiled; check Rcpp installation")

  scenarios <- list(
    list(home = 1500, away = 1500, gh = 2, ga = 0, label = "home_win_equal"),
    list(home = 1700, away = 1300, gh = 1, ga = 1, label = "draw_asymmetric"),
    list(home = 1300, away = 1700, gh = 0, ga = 3, label = "away_blowout"),
    list(home = 1500, away = 1500, gh = 1, ga = 1, label = "draw_equal"),
    list(home = 1600, away = 1400, gh = 3, ga = 2, label = "home_close_win")
  )

  for (s in scenarios) {
    # C++ path via SpielNichtSimulieren directly (mod_factor=20, home_advantage=100)
    cpp_out <- SpielNichtSimulieren(s$home, s$away, s$gh, s$ga, 20, 100)

    # R fallback via calculate_elo_update (same k_factor=20, home_advantage=100 internally)
    r_out <- calculate_elo_update(s$home, s$away, s$gh, s$ga)

    expect_equal(cpp_out[1], r_out$home_elo,
                 tolerance = 1e-4,
                 info = sprintf("scenario %s: home ELO C++ vs R", s$label))
    expect_equal(cpp_out[2], r_out$away_elo,
                 tolerance = 1e-4,
                 info = sprintf("scenario %s: away ELO C++ vs R", s$label))
  }
})

test_that("probe writes engine availability when SEASON_TRANSITION_ENGINE_PROBE is set", {
  skip_if_not(exists("SpielNichtSimulieren"),
              "SpielNichtSimulieren must be available")

  probe_path <- tempfile(fileext = ".txt")
  on.exit(unlink(probe_path), add = TRUE)

  withr::with_envvar(
    list(SEASON_TRANSITION_ENGINE_PROBE = probe_path),
    {
      update_elos_for_match(fixture_elos(), fixture_match())
    }
  )

  expect_true(file.exists(probe_path))
  expect_equal(readLines(probe_path)[1], "TRUE")
})

test_that("probe is silent when SEASON_TRANSITION_ENGINE_PROBE is unset", {
  skip_if_not(exists("SpielNichtSimulieren"),
              "SpielNichtSimulieren must be available")

  # Confirm env var is not set in the test runner.
  withr::with_envvar(
    list(SEASON_TRANSITION_ENGINE_PROBE = NA),
    {
      # Should not raise, should not write any file.
      result <- update_elos_for_match(fixture_elos(), fixture_match())
      expect_s3_class(result, "data.frame")
    }
  )
})
