# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SpielNichtSimulieren <- function(ELOHome, ELOAway, GoalsHome, GoalsAway, modFactor, homeAdvantage) {
    .Call('LeagueSimulator_SpielNichtSimulieren', PACKAGE = 'LeagueSimulator', ELOHome, ELOAway, GoalsHome, GoalsAway, modFactor, homeAdvantage)
}

