apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-shiny
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/part-of: league-simulator
    league: shiny
    action: stop
    schedule-type: daily
  annotations:
    description: "Stop Shiny updater daily at 23:40 Berlin time"
    berlin-time: "23:40"
    timezone: "Europe/Berlin"
spec:
  # 23:40 Berlin → 21:40 UTC (summer CEST)
  schedule: "40 21 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/name: pod-lifecycle-job
            app.kubernetes.io/component: scaler
            league: shiny
            action: stop
        spec:
          serviceAccountName: pod-lifecycle-manager
          restartPolicy: OnFailure
          containers:
          - name: scaler
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop:
                  - ALL
            image: bitnami/kubectl:1.28
            command:
            - kubectl
            - scale
            - deployment
            - shiny-updater
            - --replicas=0
            - -n
            - league-simulator
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            env:
            - name: DEPLOYMENT_NAME
              value: "shiny-updater"
            - name: TARGET_REPLICAS
              value: "0"
            - name: ACTION
              value: "stop"