apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-bl2-weekend
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/part-of: league-simulator
    league: bl2
    action: start
    schedule-type: weekend
  annotations:
    description: "Start 2. Bundesliga pods on weekends at 14:45 Berlin time"
    berlin-time: "14:45"
    timezone: "Europe/Berlin"
spec:
  # 14:45 Berlin → 12:45 UTC (summer CEST)
  schedule: "45 12 * * 0,6"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/name: pod-lifecycle-job
            app.kubernetes.io/component: scaler
            league: bl2
            action: start
        spec:
          serviceAccountName: pod-lifecycle-manager
          restartPolicy: OnFailure
          containers:
          - name: scaler
            image: bitnami/kubectl:1.28
            command:
            - kubectl
            - scale
            - deployment
            - league-updater-bl2
            - --replicas=1
            - -n
            - league-simulator
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            env:
            - name: DEPLOYMENT_NAME
              value: "league-updater-bl2"
            - name: TARGET_REPLICAS
              value: "1"
            - name: ACTION
              value: "start"
