apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lifecycle-manager
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: league-simulator
  annotations:
    description: "Binds pod-lifecycle-manager ServiceAccount to deployment-scaler Role"
subjects:
- kind: ServiceAccount
  name: pod-lifecycle-manager
  namespace: league-simulator
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io