apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-lifecycle-manager
  namespace: league-simulator
  labels:
    app.kubernetes.io/name: pod-lifecycle-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: league-simulator
  annotations:
    description: "ServiceAccount for CronJob-based pod lifecycle management"
automountServiceAccountToken: true